package com.businessos.enums;

public enum AuditEntityType {
    USER, COMPANY, EMPLOYEE, CLIENT,
    SERVICE_REQUEST, INVOICE, PAYMENT,
    PAYROLL, DOCUMENT, FEATURE_FLAG, SUBSCRIPTION, SUPPORT_TICKET,
    ROLE
}
