package com.zuhoocms.enums;

public enum AuditAction {
    CREATE, UPDATE, DELETE,
    LOGIN, LOGOUT,
    PASSWORD_CHANGE, EMAIL_VERIFIED,
    PERMISSION_CHANGE,
    EXPORT, UPLOAD, DOWNLOAD,
    ASSIGN, REASSIGN, ESCALATE, FIRST_RESPONSE, RESOLVE, CLOSE, REOPEN, CREATE_TICKET
}
