package com.zuhoocms.enums;

public enum LetterType {
    OFFER,
    APPOINTMENT,
    CONFIRMATION,
    PROMOTION,
    TRANSFER,
    EXPERIENCE,
    NOC,
    SALARY_CERTIFICATE,
    TERMINATION,
    RESIGNATION_ACCEPTANCE,
    WARNING,
    APPRECIATION
}
