package com.zuhoocms.enums;

public enum NotificationType {
    REQUEST_SUBMITTED, REQUEST_ASSIGNED, REQUEST_UPDATED,
    COMPLETED, REJECTED, CANCELLED,
    PAYMENT_DUE, PAYMENT_RECEIVED, INVOICE_GENERATED, REFUND_PROCESSED, REFUND_REJECTED,
    SLA_WARNING, SLA_BREACHED,
    LICENSE_EXPIRING, LICENSE_EXPIRED,
    WARRANTY_EXPIRING, WARRANTY_EXPIRED,
    ASSET_ASSIGNED, OFFBOARDING_CREATED,
    RECONCILIATION_OVERDUE, DEPRECIATION_DUE, CONTRACT_ENDING, EMPLOYEE_TERMINATED,
    DEPARTMENT_HEAD_CHANGED, HOLIDAY_PUBLISHED,
    LEAVE_REQUESTED, LEAVE_APPROVED, LEAVE_REJECTED, PAYSLIP_READY, LETTER_ISSUED,
    PERFORMANCE_REVIEW_STAGE, PERFORMANCE_REVIEW_FINALISED, PERFORMANCE_REVIEW_OVERDUE,
    WELCOME, TEAM_INVITE, ANNOUNCEMENT,
    LEAD_ASSIGNED, OPPORTUNITY_WON, OPPORTUNITY_LOST, OPPORTUNITY_STAGE_CHANGED, FOLLOW_UP_DUE,
    GENERAL
}
