package com.zuhoocms.auth.role.enums;

public enum PermissionCode {
    // LEAD
    LEAD_VIEW,
    LEAD_CREATE,
    LEAD_UPDATE,
    LEAD_DELETE,

    // OPPORTUNITY
    OPPORTUNITY_VIEW,
    OPPORTUNITY_CREATE,
    OPPORTUNITY_UPDATE,
    OPPORTUNITY_DELETE,

    // CONTACT
    CONTACT_VIEW,
    CONTACT_CREATE,
    CONTACT_UPDATE,
    CONTACT_DELETE,

    // TAG
    TAG_VIEW,
    TAG_MANAGE,

    // SUPPORT TICKET
    TICKET_VIEW,

    // WALLET
    WALLET_VIEW,

    // COMPANY
    COMPANY_VIEW,
    COMPANY_UPDATE,
    COMPANY_SETTINGS,
    COMPANY_BRANDING,

    // USER
    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    // EMPLOYEE
    EMPLOYEE_VIEW,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,

    // DEPARTMENT
    DEPARTMENT_VIEW,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,

    // DESIGNATION
    DESIGNATION_VIEW,
    DESIGNATION_CREATE,
    DESIGNATION_UPDATE,
    DESIGNATION_DELETE,

    // LEAVE
    LEAVE_VIEW,
    LEAVE_CREATE,
    LEAVE_UPDATE,
    LEAVE_CANCEL,
    LEAVE_APPROVE,
    LEAVE_REJECT,

    // LEAVE BALANCE
    LEAVE_BALANCE_VIEW,
    LEAVE_BALANCE_CREATE,
    LEAVE_BALANCE_UPDATE,
    LEAVE_BALANCE_DELETE,

    // EXPENSE
    EXPENSE_VIEW,
    EXPENSE_CREATE,
    EXPENSE_UPDATE,
    EXPENSE_DELETE,
    EXPENSE_APPROVE,
    EXPENSE_REJECT,

    // ATTENDANCE
    ATTENDANCE_VIEW,
    ATTENDANCE_MARK,
    ATTENDANCE_UPDATE,
    ATTENDANCE_APPROVE,

    // BIOMETRIC
    BIOMETRIC_VIEW,
    BIOMETRIC_MANAGE,

    // PAYROLL
    PAYROLL_VIEW,
    PAYROLL_PROCESS,
    PAYROLL_APPROVE,

    // SERVICE REQUEST
    SERVICE_REQUEST_VIEW,
    SERVICE_REQUEST_CREATE,
    SERVICE_REQUEST_ASSIGN,
    SERVICE_REQUEST_APPROVE,
    SERVICE_REQUEST_CLOSE,

    // CLIENT
    CLIENT_VIEW,
    CLIENT_CREATE,
    CLIENT_UPDATE,
    CLIENT_DELETE,

    // INVOICE
    INVOICE_VIEW,
    INVOICE_CREATE,
    INVOICE_UPDATE,
    INVOICE_DELETE,
    INVOICE_SEND,
    INVOICE_PAYMENT,
    INVOICE_CANCEL,
    INVOICE_REFUND,
    INVOICE_CREDIT_NOTE,

    // JOURNAL ENTRY
    JOURNAL_ENTRY_VIEW,
    JOURNAL_ENTRY_CREATE,
    JOURNAL_ENTRY_APPROVE,
    JOURNAL_ENTRY_POST,
    JOURNAL_ENTRY_DELETE,

    // CHART OF ACCOUNTS
    CHART_OF_ACCOUNT_VIEW,
    CHART_OF_ACCOUNT_CREATE,
    CHART_OF_ACCOUNT_UPDATE,
    CHART_OF_ACCOUNT_DELETE,

    // GENERAL LEDGER
    GENERAL_LEDGER_VIEW,
    GENERAL_LEDGER_RECONCILE,

    // BANK RECONCILIATION
    BANK_RECONCILIATION_VIEW,
    BANK_RECONCILIATION_CREATE,
    BANK_RECONCILIATION_RECONCILE,

    // ACCOUNTING PERIOD / FISCAL YEAR CLOSE
    ACCOUNTING_PERIOD_VIEW,
    ACCOUNTING_PERIOD_CLOSE,

    // VENDOR / ACCOUNTS PAYABLE
    VENDOR_VIEW,
    VENDOR_CREATE,
    VENDOR_UPDATE,
    VENDOR_DELETE,
    VENDOR_BILL_VIEW,
    VENDOR_BILL_CREATE,
    VENDOR_BILL_APPROVE,
    VENDOR_BILL_PAYMENT,
    VENDOR_BILL_CANCEL,

    // BUDGET
    BUDGET_VIEW,
    BUDGET_MANAGE,

    // FIXED ASSETS
    FIXED_ASSET_VIEW,
    FIXED_ASSET_MANAGE,

    // PAYMENT RECEIPT
    PAYMENT_RECEIPT_VIEW,
    PAYMENT_RECEIPT_CREATE,
    PAYMENT_RECEIPT_CONFIRM,
    PAYMENT_RECEIPT_DELETE,

    // FINANCIAL REPORTS
    FINANCIAL_REPORT_VIEW,

    // SOFTWARE LICENSE
    SOFTWARE_LICENSE_VIEW,
    SOFTWARE_LICENSE_CREATE,
    SOFTWARE_LICENSE_UPDATE,
    SOFTWARE_LICENSE_DELETE,
    SOFTWARE_LICENSE_ASSIGN,

    // OFFBOARDING
    OFFBOARDING_VIEW,
    OFFBOARDING_CREATE,
    OFFBOARDING_MANAGE,
    OFFBOARDING_DELETE,

    // AI
    AI_CHAT,
    AI_ADMIN,

    // SERVICEDESK CATALOG / CONFIG
    SERVICE_CATEGORY_VIEW,
    SERVICE_CATEGORY_CREATE,
    SERVICE_CATEGORY_UPDATE,
    SERVICE_CATALOG_VIEW,
    SERVICE_CATALOG_CREATE,
    SERVICE_CATALOG_UPDATE,
    SERVICE_CATALOG_DELETE,
    SERVICE_PACKAGE_VIEW,
    SERVICE_TEMPLATE_VIEW,
    SERVICE_TEMPLATE_CREATE,
    SERVICE_TEMPLATE_UPDATE,
    SERVICE_TEMPLATE_DELETE,
    WORKFLOW_VIEW,
    WORKFLOW_CREATE,
    WORKFLOW_UPDATE,
    WORKFLOW_DELETE,
    REVIEW_VIEW,
    REVIEW_DELETE,
    KNOWLEDGE_BASE_VIEW,
    KNOWLEDGE_BASE_CREATE,
    KNOWLEDGE_BASE_UPDATE,

    // SUPPORT (platform-facing helpdesk, distinct from SERVICE_REQUEST)
    SUPPORT_MESSAGE_VIEW,
    SUPPORT_CATEGORY_VIEW,
    SLA_POLICY_VIEW,
    AUDIT_LOG_VIEW,

    // HRM SUB-MODULES
    SHIFT_VIEW,
    SHIFT_CREATE,
    SHIFT_UPDATE,
    SHIFT_DELETE,
    ANNOUNCEMENT_VIEW,
    ANNOUNCEMENT_CREATE,
    ANNOUNCEMENT_UPDATE,
    ANNOUNCEMENT_DELETE,
    HOLIDAY_VIEW,
    HOLIDAY_CREATE,
    HOLIDAY_UPDATE,
    HOLIDAY_DELETE,
    LEAVE_POLICY_VIEW,
    LEAVE_POLICY_CREATE,
    LEAVE_POLICY_UPDATE,
    LEAVE_POLICY_DELETE,
    SALARY_STRUCTURE_VIEW,
    SALARY_STRUCTURE_CREATE,
    SALARY_STRUCTURE_DELETE,
    PERFORMANCE_VIEW,
    PERFORMANCE_CREATE,
    PERFORMANCE_UPDATE,
    PERFORMANCE_DELETE,
    JOB_POSTING_VIEW,
    JOB_POSTING_CREATE,
    JOB_POSTING_UPDATE,
    JOB_POSTING_DELETE,
    APPLICATION_VIEW,
    APPLICATION_CREATE,
    APPLICATION_UPDATE,
    APPLICATION_DELETE,
    LETTER_VIEW,
    LETTER_CREATE,
    LETTER_UPDATE,
    LETTER_DELETE,
    RECRUITMENT_REPORT_VIEW,

    // ATTENDANCE SUB-MODULES
    TIMESHEET_VIEW,
    TIMESHEET_APPROVE,
    SHIFT_ASSIGNMENT_VIEW,
    SHIFT_ASSIGNMENT_CREATE,
    SHIFT_ASSIGNMENT_UPDATE,
    SHIFT_ASSIGNMENT_DELETE,

    // IT ASSETS
    HARDWARE_VIEW,
    HARDWARE_CREATE,
    HARDWARE_UPDATE,
    HARDWARE_DELETE,
    ASSET_ASSIGNMENT_VIEW,
    ASSET_IMPORT_VIEW,

    // HRM ASSETS (same underlying data as IT Assets Hardware, viewed from the HRM side)
    ASSET_VIEW
}
